<#
TetherFuseNet whole-computer mode for Windows (@@VERSION@@)

Sends EVERY connection from this computer through your phone with sing-box, so no application
needs proxy settings. DNS and UDP (QUIC, voice, games) go through the phone as well.
Read this script before you run it; it is short on purpose.

Run in an ADMINISTRATOR PowerShell:  powershell -ExecutionPolicy Bypass -File .\tfn-connect.ps1
Stop: Ctrl+C

While it runs, everything except local network traffic stops if the phone goes away. That is on
purpose, so nothing quietly takes another route. Strict routing like this can upset VirtualBox,
Hyper-V and WSL networking while it runs.
#>
param(
    # Where the phone is. This file was generated by the phone, so it already knows.
    [string]$Phone = '@@HOST@@:@@PORT@@',
    # Send TCP only, UDP (QUIC, voice, games) is turned away. Try this if UDP misbehaves.
    # DNS keeps working.
    [switch]$TcpOnly,
    # Print the sing-box config that would be used and exit (needs no administrator rights)
    [switch]$PrintConfig
)

$ErrorActionPreference = 'Stop'

# sing-box 1.14 added the DNS handling this relies on
$MinMajor = 1
$MinMinor = 14

# Connections idle for longer than the phone's Socket Timeout are closed, which cuts SSH sessions
$WarnIdleSeconds = 120

function Fail([string]$Message) {
    [Console]::Error.WriteLine("tfn-connect: $Message")
    exit 1
}

function Show-InstallHint {
    Write-Host "sing-box $MinMajor.$MinMinor or newer is required. Install it with:"
    Write-Host '  winget install SagerNet.sing-box'
    Write-Host 'Then run this again.'
}

# A new install is not on the PATH of a window that was already open
function Find-SingBox {
    if ($env:SING_BOX) { return $env:SING_BOX }

    $found = Get-Command sing-box -ErrorAction SilentlyContinue
    if ($found) { return $found.Source }

    $links = Join-Path $env:LOCALAPPDATA 'Microsoft\WinGet\Links\sing-box.exe'
    if (Test-Path $links) { return $links }

    return $null
}

# Spelled [@][@] on purpose: the phone replaces every placeholder token it finds in this file
if ($Phone -like '*[@][@]*') {
    Fail 'this copy has no phone address in it, pass one: -Phone 192.168.49.1:8228'
}
if ($Phone -match '^(?<host>[0-9.]+)(:(?<port>[0-9]+))?$') {
    $PhoneHost = $Matches['host']
    $Port = if ($Matches['port']) { $Matches['port'] } else { '8228' }
} else {
    Fail 'expected an IPv4 address and a port, for example 192.168.49.1:8228'
}

# sing-box already keeps the connection to the phone on the network the phone is on, because it
# binds anything on a local subnet to that subnet's adapter. Only pin it if you must.
$Iface = $env:TFN_INTERFACE

$ConfigUrl = if ($env:TFN_CONFIG_URL) {
    $env:TFN_CONFIG_URL
} elseif ($TcpOnly) {
    "http://${PhoneHost}:$Port/sing-box.json?tcp=1"
} else {
    "http://${PhoneHost}:$Port/sing-box.json"
}

if (-not $PrintConfig) {
    $principal = [Security.Principal.WindowsPrincipal][Security.Principal.WindowsIdentity]::GetCurrent()
    if (-not $principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) {
        Fail 'run this in an ADMINISTRATOR PowerShell'
    }
    try {
        $info = (Invoke-WebRequest -UseBasicParsing -TimeoutSec 5 "http://${PhoneHost}:$Port/tfn.json").Content
    } catch {
        Fail "cannot reach TetherFuseNet at ${PhoneHost}:$Port. Join the phone's hotspot (or turn on USB tethering) and start TetherFuseNet."
    }
    if ($info -notmatch '"socks5":true') {
        Fail 'SOCKS is turned off in TetherFuseNet. With the Hotspot stopped, turn on the SOCKS4A/SOCKS5H Proxy switch (Hotspot tab, Proxy Mode), start the Hotspot and run this again.'
    }
    if ($info -match '"idle_timeout_s":(\d+)') {
        $idle = [int]$Matches[1]
        if (($idle -gt 0) -and ($idle -lt $WarnIdleSeconds)) {
            Write-Host "Note: TetherFuseNet closes connections that are idle for ${idle}s, which cuts SSH sessions and the like."
            Write-Host '      Set its Socket Timeout (Behavior tab, Adjust Socket Timeout) to 5 minutes or No Timeout.'
        }
    }

    $singBox = Find-SingBox
    if (-not $singBox) {
        Show-InstallHint
        exit 1
    }
    $versionLine = (& $singBox version | Select-Object -First 1)
    if ($versionLine -match 'sing-box version (\d+)\.(\d+)') {
        $major = [int]$Matches[1]
        $minor = [int]$Matches[2]
        if (($major -lt $MinMajor) -or (($major -eq $MinMajor) -and ($minor -lt $MinMinor))) {
            Show-InstallHint
            exit 1
        }
    } else {
        Show-InstallHint
        exit 1
    }
}

try {
    $raw = (Invoke-WebRequest -UseBasicParsing -TimeoutSec 10 $ConfigUrl).Content
} catch {
    Fail "could not download the sing-box config from $ConfigUrl"
}

$patched = $raw
if ($Iface) {
    $ifaceJson = "$Iface".Replace('\', '\\').Replace('"', '\"')
    $patched = $raw.Replace('"bind_interface": ""', '"bind_interface": "' + $ifaceJson + '"')
}

if ($PrintConfig) {
    Write-Output $patched
    exit 0
}

# Go's JSON parser rejects a byte order mark, so do not let PowerShell add one
$config = Join-Path ([IO.Path]::GetTempPath()) ('tfn-singbox-' + [Guid]::NewGuid().ToString('N') + '.json')
[IO.File]::WriteAllText($config, $patched, (New-Object Text.UTF8Encoding($false)))
try {
    & $singBox check -c $config
    if ($LASTEXITCODE -ne 0) { Fail 'sing-box rejected the generated config' }

    Write-Host "Sending everything on this computer through ${PhoneHost}:$Port. Press Ctrl+C to disconnect."
    & $singBox run -c $config
} finally {
    Remove-Item -Force -ErrorAction SilentlyContinue $config
}
