#!/bin/sh
#
# TetherFuseNet whole-computer mode for Linux and macOS (@@VERSION@@)
#
# Sends EVERY connection from this computer through your phone with sing-box, so no application
# needs proxy settings. DNS and UDP (QUIC, voice, games) go through the phone as well.
# Read this script before you run it; it is short on purpose.
#
# Run:  sudo sh tfn-connect.sh
# Stop: Ctrl+C
#
# While it runs, everything except local network traffic stops if the phone goes away. That is on
# purpose, so nothing quietly takes another route.

set -eu

# Where the phone is. This file was generated by the phone, so it already knows.
DEFAULT_TARGET='@@HOST@@:@@PORT@@'

# sing-box 1.14 added the DNS handling this relies on
MIN_MAJOR=1
MIN_MINOR=14

# Connections idle for longer than the phone's Socket Timeout are closed, which cuts SSH sessions
WARN_IDLE_SECONDS=120

say() {
  printf '%s\n' "$*"
}

fail() {
  printf 'tfn-connect: %s\n' "$*" >&2
  exit 1
}

usage() {
  say 'Usage: sudo sh tfn-connect.sh [PHONE_IP[:PORT]] [--tcp-only] [--print-config]'
  say ''
  say '  PHONE_IP[:PORT]  the phone running TetherFuseNet (default: the phone that served this file)'
  say '  --tcp-only       send TCP only, UDP (QUIC, voice, games) is turned away. Try this if UDP'
  say '                   misbehaves; DNS keeps working'
  say '  --print-config   print the sing-box config that would be used and exit (needs no root)'
  say ''
  say 'Environment: TFN_INTERFACE  pin the connection to the phone to this network interface (rarely needed)'
  say '             SING_BOX       the sing-box program to use'
  say ''
  say 'If sing-box was killed instead of stopped with Ctrl+C and Linux networking misbehaves:'
  say '  sudo nft delete table inet sing-box'
}

install_hint() {
  say "sing-box $MIN_MAJOR.$MIN_MINOR or newer is required. Install it with:"
  if command -v pacman >/dev/null 2>&1; then
    say '  sudo pacman -S sing-box'
  elif command -v brew >/dev/null 2>&1; then
    say '  brew install sing-box'
  else
    say '  https://sing-box.sagernet.org/installation/package-manager/'
  fi
}

# sudo often drops the PATH that finds a Homebrew install
find_sing_box() {
  if [ -n "${SING_BOX:-}" ]; then
    printf '%s\n' "$SING_BOX"
    return 0
  fi
  if command -v sing-box >/dev/null 2>&1; then
    command -v sing-box
    return 0
  fi
  for candidate in /opt/homebrew/bin/sing-box /usr/local/bin/sing-box /home/linuxbrew/.linuxbrew/bin/sing-box; do
    if [ -x "$candidate" ]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done
  return 1
}

PRINT_ONLY=0
TCP_ONLY=0
TARGET=$DEFAULT_TARGET
for arg in "$@"; do
  case "$arg" in
    --print-config) PRINT_ONLY=1 ;;
    --tcp-only) TCP_ONLY=1 ;;
    -h | --help)
      usage
      exit 0
      ;;
    -*) fail "unknown option: $arg" ;;
    *) TARGET=$arg ;;
  esac
done

case "$TARGET" in
  # Spelled [@][@] on purpose: the phone replaces every placeholder token it finds in this file
  *[@][@]*) fail 'this copy has no phone address in it, pass one: sh tfn-connect.sh 192.168.49.1:8228' ;;
  *:*)
    HOST=${TARGET%:*}
    PORT=${TARGET##*:}
    ;;
  *)
    HOST=$TARGET
    PORT=8228
    ;;
esac

case "$HOST$PORT" in
  '' | *[!0-9.]*) fail "expected an IPv4 address and a port, for example 192.168.49.1:8228" ;;
esac

command -v curl >/dev/null 2>&1 || fail 'curl is required'

OS=$(uname -s)
case "$OS" in
  Linux)
    # Cleaner and faster routing, but it needs nftables
    REDIRECT=false
    if command -v nft >/dev/null 2>&1; then
      REDIRECT=true
    fi
    ;;
  Darwin) REDIRECT=false ;;
  *) fail "unsupported system: $OS (this script is for Linux and macOS)" ;;
esac

# sing-box already keeps the connection to the phone on the network the phone is on, because it
# binds anything on a local subnet to that subnet's interface. Only pin it if you must.
IFACE=${TFN_INTERFACE:-}

CONFIG_URL=${TFN_CONFIG_URL:-"http://$HOST:$PORT/sing-box.json"}
if [ "$TCP_ONLY" -eq 1 ] && [ -z "${TFN_CONFIG_URL:-}" ]; then
  CONFIG_URL="$CONFIG_URL?tcp=1"
fi

if [ "$PRINT_ONLY" -eq 0 ]; then
  [ "$(id -u)" -eq 0 ] || fail 'run this as root:  sudo sh tfn-connect.sh'

  INFO=$(curl -fsS --max-time 5 "http://$HOST:$PORT/tfn.json") ||
    fail "cannot reach TetherFuseNet at $HOST:$PORT. Join the phone's hotspot (or turn on USB tethering) and start TetherFuseNet."
  case "$INFO" in
    *'"socks5":true'*) ;;
    *) fail 'SOCKS is turned off in TetherFuseNet. With the Hotspot stopped, turn on the SOCKS4A/SOCKS5H Proxy switch (Hotspot tab, Proxy Mode), start the Hotspot and run this again.' ;;
  esac

  IDLE=$(printf '%s' "$INFO" | sed -n 's/.*"idle_timeout_s":\([0-9][0-9]*\).*/\1/p')
  if [ -n "$IDLE" ] && [ "$IDLE" -gt 0 ] && [ "$IDLE" -lt "$WARN_IDLE_SECONDS" ]; then
    say "Note: TetherFuseNet closes connections that are idle for ${IDLE}s, which cuts SSH sessions and the like."
    say '      Set its Socket Timeout (Behavior tab, Adjust Socket Timeout) to 5 minutes or No Timeout.'
  fi

  SING_BOX_BIN=$(find_sing_box) || {
    install_hint
    exit 1
  }

  # "sing-box version 1.14.2" -> "1 14"
  # shellcheck disable=SC2046
  set -- $("$SING_BOX_BIN" version 2>/dev/null | sed -n 's/^sing-box version \([0-9][0-9]*\)\.\([0-9][0-9]*\).*/\1 \2/p' | head -n 1)
  if [ "${1:-0}" -lt "$MIN_MAJOR" ] || { [ "${1:-0}" -eq "$MIN_MAJOR" ] && [ "${2:-0}" -lt "$MIN_MINOR" ]; }; then
    install_hint
    exit 1
  fi
fi

RAW=$(curl -fsS --max-time 10 "$CONFIG_URL") || fail "could not download the sing-box config from $CONFIG_URL"

# The phone cannot know what this computer has, so these two are filled in here
patch_config() {
  if [ -n "$IFACE" ]; then
    sed -e "s|\"bind_interface\": \"\"|\"bind_interface\": \"$IFACE\"|" \
      -e "s|\"auto_redirect\": false|\"auto_redirect\": $REDIRECT|"
  else
    sed -e "s|\"auto_redirect\": false|\"auto_redirect\": $REDIRECT|"
  fi
}

if [ "$PRINT_ONLY" -eq 1 ]; then
  printf '%s\n' "$RAW" | patch_config
  exit 0
fi

CONFIG=$(mktemp "${TMPDIR:-/tmp}/tfn-singbox.XXXXXX") || fail 'cannot create a temporary file'
cleanup() {
  rm -f "$CONFIG"
}
trap cleanup EXIT
trap 'exit 130' INT
trap 'exit 143' TERM

printf '%s\n' "$RAW" | patch_config >"$CONFIG"

"$SING_BOX_BIN" check -c "$CONFIG" || fail 'sing-box rejected the generated config'

say "Sending everything on this computer through $HOST:$PORT. Press Ctrl+C to disconnect."
"$SING_BOX_BIN" run -c "$CONFIG"
